# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Move_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 419)
        MainWindow.setMinimumSize(QtCore.QSize(505, 419))
        MainWindow.setMaximumSize(QtCore.QSize(505, 419))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushB_yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_yes.setGeometry(QtCore.QRect(130, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushB_yes.setFont(font)
        self.pushB_yes.setObjectName("pushB_yes")
        self.pushB_no = QtWidgets.QPushButton(self.centralwidget)
        self.pushB_no.setGeometry(QtCore.QRect(260, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushB_no.setFont(font)
        self.pushB_no.setObjectName("pushB_no")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 335, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushB_no.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Хочу большую пенсию"))
        self.pushB_yes.setText(_translate("MainWindow", "Да"))
        self.pushB_no.setText(_translate("MainWindow", "Нет"))
        self.label.setText(_translate("MainWindow", "Вы хотите, чтобы Вам увеличили размер пенсии?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
